export const environment = {
  production: true,
  env: "prod",
  BASE_HREF: "/itcna/apigateway-iot/api/physecadmin",
  endpoints: {
    "getLocaleLanguages": "assets/api/languages.json",
    "getIncidents": "assets/api/incidents.json",
    "getIncidentsGlobal": "assets/api/occurenceData.json",
    "getFilteredIncidents": "assets/api/incidents-filtered.json",
    "getIncidentDetails": "assets/api/incident-details.json",
    "getStaffDetails": "assets/api/staffManagementData.json",
    // "getVehicleTrackData": "assets/api/vehicleTrackData.json",
    "getVehicleTrackData": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/vehicle-management/api/v1/reports/vehicle/log/list",
    // "getOccurenceData": "assets/api/occurenceData.json",
    "getOccurenceData": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/occmgmt/api/v1/getOccurrence",
    "getOccurrenceReport": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/occmgmt/api/v1/downloadOccurrenceReport",
    "getOccurrenceCount": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/occmgmt/api/v1/getOccurrenceCount",
    "getCabData": "assets/api/cabData.json",
    "getMaterialData": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/material-management/material/v1/materialLogReport",
    "getMaterialLogCount": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/material-management/material/v2/logCount?startTime={startTime}&endTime={endTime}",
    // "getMaterialReport":"assets/api/material-report.xls",
    "getMaterialReport": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/material-management/material/v1/generateReport",
    "getAttendanceData": "assets/api/attendanceData.json",
    "getNotificationsData": "assets/api/notifications.json",
    "getOfficeLocation": "assets/api/officeLocations.json",
    "getTimelineData": "assets/api/timelinedata.json",
    "getCountriesData": "assets/api/countries.json",
    "getPopularLocations": "assets/api/popularOfficeLocations.json",
    // "getVehicleParkingOverview": "assets/api/vehicle-data.json",
    "getVehicleParkingOverview": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/vehicle-management/api/v1/reports/vehicle/log",
    "getComplianceGlobalData": "assets/api/compliance-global-data.json",
    "getShortageDataGlobal": "assets/api/shortage-global-data.json",
    "getDeploymentData": "assets/api/deployment.json",
    "ssoLogin": "https://mbei.vmware.com:9090/auth-server/oauth/authorize?response_type=code&redirect_uri=https://services.itcna.vmware.com/itcna/apigateway-iot/api/physecadmin/authpass&client_id=PhySecWeb&idp=vidm",
    "getAccessToken": "/auth-server/oauth/token?grant_type=authorization_code&code={authCode}&redirect_uri={redirectUrl}&scope=read",
    "getNewAccessToken": "/auth-server/oauth/token?grant_type=refresh_token&refresh_token={refreshToken}&redirect_uri={redirectUrl}&scope=read",
    "getUserDetails": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/staff-mgmt-service/staffmgmt/v1/getSecPersonnelDetails",
    "peopleSearchUrl": "/people-search/search?entityType=user&q={userEmail}&partnerType=vmware",
    "getImage": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/staff-mgmt-service/staff/v1/getImage/",
    "sendBroadcastNotification": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/staff-mgmt-service/staffmgmt/v1/notification/send",
    "getNotificationForOfcLocation": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/staff-mgmt-service/staffmgmt/v1/notification/getMsg",
    "getLastKnownBriefingReport": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/staff-mgmt-service/staffmgmt/v1/getLastKnownBriefingReport",
    "sendBriefingReport": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/staff-mgmt-service/staffmgmt/v1/addBriefingReport",
    "getShiftDetails": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/staff-mgmt-service/staffmgmt/v1/getShifts",
    "sendUserDeviceInfoForFirebase": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/staff-mgmt-service/staff/v1/notification/user/device",
    "getCabLogOverview": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/vehicle-management/api/v1/reports/cab/log/overview",
    "getCabLog": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/vehicle-management/api/v1/reports/cab/log",
    "getCabLogDownload": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/vehicle-management/api/v1/reports/cab/log/download",
    "getCabServiceTypes": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/vehicle-management/api/v1/cab/service/types",
    "getCabReport": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/vehicle-management/api/v1/reports/cab/log/download",
    "getVehicleTypes": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/vehicle-management/api/v1/vehicle/types",
    "getParkingTypes": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/vehicle-management/api/v1/parking/types",
    "getStaffCount": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/staff-mgmt-service/staffmgmt/v1/securityStaffCount",
    "getAttendanceReport": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/staff-mgmt-service/staffmgmt/v1/getAttendanceReport",
    "searchSecurityPersonnel": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/staff-mgmt-service/staffmgmt/v1/searchSecurityStaff",
    "getstaffCompliance": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/staff-mgmt-service/staffmgmt/v1/getComplianceTask",
    "logoutURL": "https://www.vmware.com"
  },
  "redirectUrl": "https://services.itcna.vmware.com/itcna/apigateway-iot/api/physecadmin/authpass",
  "clientId": "PhySecWeb",
  "clientSecret": "UGh5U2VjV2ViOjczZTQ5Y2I0LWM1MzYtNGU5Ni05M2E1LTY1ZTA4YWIzZTc2MQ==",
  "appId": "SMIE-VMWARE-412869",
  "tenantId": "SMIE-VMWARE-0298",
  "loginScreenWait": 5000,
  "appPath": "/itcna/apigateway-iot/api/physecadmin",
  // Chart configurations for the pie charts
  FIREBASE_CONFIG: {
    apiKey: "AIzaSyDogE1lUlmWam0tqLqI5RMkFUYWiuhnHQA",
    authDomain: "physical-security-manager.firebaseapp.com",
    databaseURL: "https://physical-security-manager.firebaseio.com",
    projectId: "physical-security-manager",
    storageBucket: "physical-security-manager.appspot.com",
    messagingSenderId: "495197375055"
  },
  "fireBaseUrl": "https://PUSH-NOTIFICATION/api/v1/push-notification/user/device"

};
